package com.didasepidos.didasepidoswebapp.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

@Entity
@Table(name="generated_authors")
@IdClass(AIGRId.class)
public class AuthorIdGenerationRecord {
	
	@Id
	private String origin;
	
	@Id
	private Date datetime;
	
	public AuthorIdGenerationRecord() {}

	public AuthorIdGenerationRecord(String origin, Date datetime) {
		super();
		this.origin = origin;
		this.datetime = datetime;
	}

	public String getOrigin() {
		return origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	public Date getDatetime() {
		return datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((datetime == null) ? 0 : datetime.hashCode());
		result = prime * result + ((origin == null) ? 0 : origin.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AuthorIdGenerationRecord other = (AuthorIdGenerationRecord) obj;
		if (datetime == null) {
			if (other.datetime != null)
				return false;
		} else if (!datetime.equals(other.datetime))
			return false;
		if (origin == null) {
			if (other.origin != null)
				return false;
		} else if (!origin.equals(other.origin))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Author ID generated by " + origin + " at " + datetime;
	}
	
	
}

class AIGRId implements Serializable {
	
	private static final long serialVersionUID = 1L;

	@Column(name="origin")
	private String origin;
	
	@Column(name="datetime")
	private Date datetime;
	
	public AIGRId() {}

	public AIGRId(String origin, Date datetime) {
		super();
		this.origin = origin;
		this.datetime = datetime;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((datetime == null) ? 0 : datetime.hashCode());
		result = prime * result + ((origin == null) ? 0 : origin.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AIGRId other = (AIGRId) obj;
		if (datetime == null) {
			if (other.datetime != null)
				return false;
		} else if (!datetime.equals(other.datetime))
			return false;
		if (origin == null) {
			if (other.origin != null)
				return false;
		} else if (!origin.equals(other.origin))
			return false;
		return true;
	}
	
}
